version: '3.8'

services:
  web:    
    build:
      context: ./metro_assist
    env_file:
      - ./env/.env.local
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py initialize_data && python manage.py load_data && python manage.py runserver 0.0.0.0:8000"
    restart: always
    expose:
      - 8000
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: postgres:16.1
    env_file:
      - ./env/.env.local      
    command: ["postgres", "-c", "max_connections=150"]
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: '3G'
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw,size=20G
    restart: always
    ports:
      - '6543:5432'

volumes:
  postgres_data:
