# Generated by Django 5.0.6 on 2024-06-04 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('has_eks', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('shift', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=50)),
                ('work_phone', models.CharField(max_length=20)),
                ('personal_phone', models.CharField(max_length=20)),
                ('tab_number', models.CharField(max_length=8)),
                ('light_duty', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_station', models.CharField(max_length=50)),
                ('arrival_station', models.CharField(max_length=50)),
                ('meeting_point', models.CharField(max_length=255)),
                ('arrival_point', models.CharField(max_length=255)),
                ('request_date', models.DateTimeField()),
                ('method_of_request', models.CharField(max_length=50)),
                ('number_of_passengers', models.IntegerField()),
                ('request_category', models.CharField(max_length=50)),
                ('number_of_employees', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_time', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('additional_shift', models.BooleanField(default=False)),
                ('training_date', models.DateField(blank=True, null=True)),
                ('training_end_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
    ]
