# Generated by Django 5.0.6 on 2024-06-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
