# Generated by Django 5.0.6 on 2024-06-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='category',
            field=models.CharField(choices=[('IZT', '(ИЗТ) Инвалид по зрению (тотальный)'), ('IZ', '(ИЗ) Инвалид по зрению с остаточным зрением'), ('IS', '(ИС) Инвалид по слуху'), ('IK', '(ИК) Инвалид колясочник'), ('IO', '(ИО) Инвалид опорник'), ('DI', '(ДИ) Ребенок инвалид'), ('PL', '(ПЛ) Пожилой человек'), ('RD', '(РД) Родители с детьми'), ('RDK', '(РДК) Родители с детскими колясками'), ('OGD', '(ОГД) Организованные группы детей'), ('OV', '(ОВ) Временно маломобильные'), ('IU', '(ИУ) Люди с ментальной инвалидностью')], max_length=3),
        ),
    ]
